FROM python:3.10-slim

WORKDIR /app

# Установка необходимых инструментов
RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/app

ENV PYTHONPATH=/app

CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]